"""
Curl test command generator for API testing.
"""

import json
import logging
from typing import Dict, List, Optional, Any
from pathlib import Path
import shlex

from ..models.test_models import APITestConfig


class CurlTestGenerator:
    """Generates curl commands for API testing."""
    
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url.rstrip('/')
        self.logger = logging.getLogger(f"{__name__}.CurlTestGenerator")
    
    def generate_evaluation_request(self, config: Dict[str, Any]) -> str:
        """Generate curl command for creating an evaluation."""
        data = {
            "model_id": config.get("model_id", "test_model"),
            "tasks": config.get("tasks", ["hellaswag"]),
            "config": config.get("evaluation_config", {})
        }
        
        json_data = json.dumps(data)
        
        curl_cmd = [
            "curl",
            "-X", "POST",
            "-H", "Content-Type: application/json",
            "-d", json_data,
            f"{self.base_url}/api/v1/evaluations"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_status_check(self, evaluation_id: str) -> str:
        """Generate curl command for checking evaluation status."""
        curl_cmd = [
            "curl",
            "-X", "GET",
            "-H", "Accept: application/json",
            f"{self.base_url}/api/v1/evaluations/{evaluation_id}/status"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_result_retrieval(self, evaluation_id: str) -> str:
        """Generate curl command for retrieving evaluation results."""
        curl_cmd = [
            "curl",
            "-X", "GET",
            "-H", "Accept: application/json",
            f"{self.base_url}/api/v1/evaluations/{evaluation_id}/results"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_list_evaluations(self) -> str:
        """Generate curl command for listing evaluations."""
        curl_cmd = [
            "curl",
            "-X", "GET",
            "-H", "Accept: application/json",
            f"{self.base_url}/api/v1/evaluations"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_list_tasks(self) -> str:
        """Generate curl command for listing available tasks."""
        curl_cmd = [
            "curl",
            "-X", "GET",
            "-H", "Accept: application/json",
            f"{self.base_url}/api/v1/tasks"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_list_adapters(self) -> str:
        """Generate curl command for listing available adapters."""
        curl_cmd = [
            "curl",
            "-X", "GET",
            "-H", "Accept: application/json",
            f"{self.base_url}/api/v1/adapters"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_cancel_evaluation(self, evaluation_id: str) -> str:
        """Generate curl command for cancelling an evaluation."""
        curl_cmd = [
            "curl",
            "-X", "DELETE",
            "-H", "Accept: application/json",
            f"{self.base_url}/api/v1/evaluations/{evaluation_id}"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_health_check(self) -> str:
        """Generate curl command for health check."""
        curl_cmd = [
            "curl",
            "-X", "GET",
            "-H", "Accept: application/json",
            f"{self.base_url}/health"
        ]
        
        return " ".join(shlex.quote(arg) for arg in curl_cmd)
    
    def generate_comprehensive_test_script(self, config: Dict[str, Any]) -> str:
        """Generate a comprehensive test script with multiple curl commands."""
        script_lines = [
            "#!/bin/bash",
            "# Comprehensive API Test Script",
            "# Generated by EvaluationEngineV1_0 Testing Framework",
            "",
            "set -e  # Exit on any error",
            "",
            "echo '=== EvaluationEngineV1_0 API Test Script ==='",
            "echo",
            "",
            "# Configuration",
            f"BASE_URL='{self.base_url}'",
            "EVALUATION_ID=''",
            "",
            "# Function to extract evaluation ID from response",
            "extract_evaluation_id() {",
            "    echo $1 | grep -o '\"evaluation_id\":\"[^\"]*\"' | cut -d'\"' -f4",
            "}",
            "",
            "# Function to check if command succeeded",
            "check_success() {",
            "    if [ $? -eq 0 ]; then",
            "        echo '✓ Success'",
            "    else",
            "        echo '✗ Failed'",
            "        exit 1",
            "    fi",
            "}",
            "",
            "echo '1. Health Check'",
            "echo '==============='",
            self.generate_health_check(),
            "check_success",
            "echo",
            "",
            "echo '2. List Available Tasks'",
            "echo '======================'",
            self.generate_list_tasks(),
            "check_success",
            "echo",
            "",
            "echo '3. List Available Adapters'",
            "echo '========================='",
            self.generate_list_adapters(),
            "check_success",
            "echo",
            "",
            "echo '4. Create Evaluation'",
            "echo '==================='",
            f"RESPONSE=$({self.generate_evaluation_request(config)})",
            "check_success",
            "echo $RESPONSE",
            "EVALUATION_ID=$(extract_evaluation_id \"$RESPONSE\")",
            "echo \"Evaluation ID: $EVALUATION_ID\"",
            "echo",
            "",
            "echo '5. Check Evaluation Status'",
            "echo '========================='",
            "echo 'Waiting for evaluation to start...'",
            "sleep 2",
            "curl -X GET -H 'Accept: application/json' \"$BASE_URL/api/v1/evaluations/$EVALUATION_ID/status\"",
            "check_success",
            "echo",
            "",
            "echo '6. Monitor Evaluation Progress'",
            "echo '============================='",
            "for i in {1..10}; do",
            "    echo \"Check $i:\"",
            "    STATUS_RESPONSE=$(curl -s -X GET -H 'Accept: application/json' \"$BASE_URL/api/v1/evaluations/$EVALUATION_ID/status\")",
            "    echo $STATUS_RESPONSE",
            "    STATUS=$(echo $STATUS_RESPONSE | grep -o '\"status\":\"[^\"]*\"' | cut -d'\"' -f4)",
            "    echo \"Status: $STATUS\"",
            "    ",
            "    if [ \"$STATUS\" = \"completed\" ] || [ \"$STATUS\" = \"failed\" ]; then",
            "        break",
            "    fi",
            "    ",
            "    echo 'Waiting...'",
            "    sleep 3",
            "done",
            "echo",
            "",
            "echo '7. Get Evaluation Results'",
            "echo '========================'",
            "if [ \"$STATUS\" = \"completed\" ]; then",
            "    curl -X GET -H 'Accept: application/json' \"$BASE_URL/api/v1/evaluations/$EVALUATION_ID/results\"",
            "    check_success",
            "else",
            "    echo 'Evaluation not completed, skipping results retrieval'",
            "fi",
            "echo",
            "",
            "echo '8. List All Evaluations'",
            "echo '======================'",
            self.generate_list_evaluations(),
            "check_success",
            "echo",
            "",
            "echo '=== Test Script Completed ==='",
            "echo 'All API endpoints tested successfully!'"
        ]
        
        return "\n".join(script_lines)
    
    def generate_concurrent_test_script(self, config: Dict[str, Any], 
                                      concurrent_requests: int = 3) -> str:
        """Generate a script for testing concurrent API requests."""
        script_lines = [
            "#!/bin/bash",
            "# Concurrent API Test Script",
            "# Tests multiple simultaneous evaluation requests",
            "",
            "set -e",
            "",
            "echo '=== Concurrent API Test ==='",
            f"CONCURRENT_REQUESTS={concurrent_requests}",
            f"BASE_URL='{self.base_url}'",
            "",
            "# Array to store evaluation IDs",
            "declare -a EVALUATION_IDS",
            "",
            "echo \"Starting $CONCURRENT_REQUESTS concurrent evaluations...\"",
            "",
            "# Start concurrent evaluations",
            f"for i in $(seq 1 $CONCURRENT_REQUESTS); do",
            "    echo \"Starting evaluation $i...\"",
            "    RESPONSE=$(curl -s -X POST -H 'Content-Type: application/json' \\",
            f"        -d '{json.dumps(config)}' \\",
            f"        \"$BASE_URL/api/v1/evaluations\")",
            "    ",
            "    EVAL_ID=$(echo $RESPONSE | grep -o '\"evaluation_id\":\"[^\"]*\"' | cut -d'\"' -f4)",
            "    EVALUATION_IDS[$i]=$EVAL_ID",
            "    echo \"  Evaluation $i ID: $EVAL_ID\"",
            "done",
            "",
            "echo",
            "echo 'Monitoring all evaluations...'",
            "",
            "# Monitor all evaluations",
            "for round in {1..20}; do",
            "    echo \"=== Monitoring Round $round ===\"",
            "    completed_count=0",
            "    ",
            "    for i in $(seq 1 $CONCURRENT_REQUESTS); do",
            "        eval_id=${EVALUATION_IDS[$i]}",
            "        status_response=$(curl -s \"$BASE_URL/api/v1/evaluations/$eval_id/status\")",
            "        status=$(echo $status_response | grep -o '\"status\":\"[^\"]*\"' | cut -d'\"' -f4)",
            "        progress=$(echo $status_response | grep -o '\"progress\":[0-9.]*' | cut -d':' -f2)",
            "        ",
            "        echo \"  Evaluation $i ($eval_id): $status (${progress}%)\"",
            "        ",
            "        if [ \"$status\" = \"completed\" ] || [ \"$status\" = \"failed\" ]; then",
            "            ((completed_count++))",
            "        fi",
            "    done",
            "    ",
            "    if [ $completed_count -eq $CONCURRENT_REQUESTS ]; then",
            "        echo 'All evaluations completed!'",
            "        break",
            "    fi",
            "    ",
            "    echo 'Waiting for more completions...'",
            "    sleep 5",
            "done",
            "",
            "echo",
            "echo '=== Final Results ==='",
            "for i in $(seq 1 $CONCURRENT_REQUESTS); do",
            "    eval_id=${EVALUATION_IDS[$i]}",
            "    echo \"Results for Evaluation $i ($eval_id):\"",
            "    curl -s \"$BASE_URL/api/v1/evaluations/$eval_id/results\" | head -10",
            "    echo",
            "done",
            "",
            "echo '=== Concurrent Test Completed ==='",
        ]
        
        return "\n".join(script_lines)
    
    def save_test_script(self, script_content: str, output_path: Path) -> None:
        """Save test script to file."""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(script_content)
        
        # Make script executable
        output_path.chmod(0o755)
        
        self.logger.info(f"Test script saved to {output_path}")
    
    def generate_curl_examples_file(self, config: Dict[str, Any]) -> str:
        """Generate a file with curl command examples."""
        examples = [
            "# EvaluationEngineV1_0 API - Curl Command Examples",
            "# ================================================",
            "",
            "# 1. Health Check",
            self.generate_health_check(),
            "",
            "# 2. List Available Tasks",
            self.generate_list_tasks(),
            "",
            "# 3. List Available Adapters", 
            self.generate_list_adapters(),
            "",
            "# 4. Create Evaluation",
            self.generate_evaluation_request(config),
            "",
            "# 5. Check Evaluation Status (replace EVALUATION_ID)",
            self.generate_status_check("EVALUATION_ID"),
            "",
            "# 6. Get Evaluation Results (replace EVALUATION_ID)",
            self.generate_result_retrieval("EVALUATION_ID"),
            "",
            "# 7. List All Evaluations",
            self.generate_list_evaluations(),
            "",
            "# 8. Cancel Evaluation (replace EVALUATION_ID)",
            self.generate_cancel_evaluation("EVALUATION_ID"),
            "",
            "# Example with specific configuration:",
            f"# Model: {config.get('model_id', 'test_model')}",
            f"# Tasks: {', '.join(config.get('tasks', ['hellaswag']))}",
            "",
            "# Note: Replace EVALUATION_ID with actual evaluation ID from create response"
        ]
        
        return "\n".join(examples)


def create_curl_test_generator(base_url: str = "http://localhost:8000") -> CurlTestGenerator:
    """Factory function to create a curl test generator."""
    return CurlTestGenerator(base_url=base_url)